version: '3'
services:
  PostgreSQL:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  my-app:
    image: 'travel:latest'
    ports:
      - '8080:8080'
    depends_on:
      PostgreSQL:
        condition: service_healthy

#  prometheus:
#    image: prom/prometheus
#    container_name: travel-prometheus
#    volumes:
#      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - 9090:9090
#    depends_on:
#      my-app:
#        condition: service_started
#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    ports:
#      - 3000:3000
#    env_file:
#      - ./monitoring/grafana.yml
#    depends_on:
#      prometheus:
#        condition: service_started
