version: '3'
services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=travel
      - MYSQL_USER=flyway
      - MYSQL_PASSWORD=flyway
    ports:
      - 3306:3306
    healthcheck:
      test: "mysqladmin -u root -ppassword ping"
      interval: 10s
      retries: 10

  my-app:
    image: 'travel:latest'
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: test
    depends_on:
      mysqldb:
        condition: service_healthy
  prometheus:
    image: prom/prometheus
    container_name: travel-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      my-app:
        condition: service_started
