version: "3.8"

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=travel
      #- MYSQL_USER=flyway
      #- MYSQL_PASSWORD=flyway
    ports:
      - 3306:3306