version: "3.8"
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=travel
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=flyway
      - MYSQL_PASSWORD=flyway
    ports:
      - 3306:3306