version: '3'
services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=travel
      - MYSQL_USER=flyway
      - MYSQL_PASSWORD=flyway
    ports:
      - 3306:3306
    healthcheck:
      test: "mysqladmin -u root -ppassword ping"
      interval: 10s
      retries: 10

  my-app:
    image: 'travel:latest'
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: test
    depends_on:
      mysqldb:
        condition: service_healthy
  prometheus:
    image: prom/prometheus:v2.30.3
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/monitoring
    ports:
      - "9090:9090"
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      my-app:
        condition: service_started
    networks:
      - my-app
#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    ports:
#      - 3000:3000
#    env_file:
#      - ./monitoring/grafana.yml
#    depends_on:
#      prometheus:
#        condition: service_started
volumes :
  prometheus-data :
networks:
  my-app:
    driver: bridge