version: '3'
services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=travel
      - MYSQL_USER=flyway
      - MYSQL_PASSWORD=flyway
    ports:
      - 3306:3306
    healthcheck:
      test: "mysqladmin -u root -ppassword ping"
      interval: 10s
      retries: 10
  my-app:
    image: 'travel:latest'
    ports:
      - '8080:8080'
    environment:
        SPRING_PROFILES_ACTIVE: test
    depends_on:
      - mysqldb
  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    ports:
      - '3000:3000'
    #volumes:
      #- grafana_data:/var/lib/grafana
  #volumes:
    #grafana_data: { }