spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel
    username: root
    password: password
  jpa:
    #hibernate.ddl-auto: update
    #generate-ddl: true
    show-sql: true
  flyway:
    user: root
    password: password
    schemas: travel
    url: jdbc:mysql://localhost:3306/travel
    locations: classpath:db/migration
    baseline-on-migrate: true
    create-schemas: true
    enabled: true
  logging:
    level:
      root: debug
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
swagger:
  host:
    url=http://localhost:8080:
logging:
  level:
    org:
      hibernate:
        SQL=DEBUG:

    springframework:
        testloglevel=TRACE: