spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/travel
    username: root
    password: password
  jpa:
    #hibernate.ddl-auto: update
    #generate-ddl: true
    show-sql: true
  flyway:
    user: root
    password: password
    schemas: travel
    url: jdbc:mysql://mysqldb:3306/travel
    locations: classpath:db/migration
    baseline-on-migrate: true
    create-schemas: true
    enabled: true
  logging:
    level:
      root: debug
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  secret: javainuse
swagger:
  host:
    url=http://localhost:8080:
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false