spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/arun
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    #generate-ddl: true
    show-sql: true