spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://PostgreSQL:5432/postgres
    username: postgres
    password: password
  jpa:
    open-in-view: false
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
#  flyway:
#    user: postgres
#    password: password
#    url: jdbc:postgresql://PostgreSQL:5432/postgres
#    locations: classpath:db/migration
#    baseline-on-migrate: true
#    create-schemas: true
#    enabled: true
  logging:
    level:
      root: debug
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
swagger:
  host:
    url=http://localhost:8080:
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always